version: '3.8'

services:
  redis-reactive:
    image: cr.yandex/mirror/redis:latest
    container_name: redis-reactive
    ports:
      - "6379:6379"
    networks:
      - market-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis-reactive
    networks:
      - market-network

  storefront-app:
    build:
      context: ./storefront-app
      dockerfile: Dockerfile
    container_name: storefront-app
    ports:
      - "8080:8080"
    environment:
      - PAYMENT_SERVICE_URL=http://payment-service:8081
      - SPRING_DATA_REDIS_HOST=redis-reactive
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - payment-service
      - redis-reactive
    networks:
      - market-network

networks:
  market-network:
    driver: bridge
