spring.application.name=my-market-app

spring.r2dbc.url=r2dbc:h2:mem:///maindb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.web=DEBUG

spring.codec.max-in-memory-size=10MB

spring.webflux.multipart.max-file-size=5MB
spring.webflux.multipart.max-request-size=10MB


